---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  yarn: true
  directories:
    - $HOME/.cache # includes bowers cache

env:
  - EMBER_TRY_SCENARIO=ember-1.13
  - EMBER_TRY_SCENARIO=ember-lts-2.4
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add phantomjs-prebuilt bower

install:
  - yarn install --no-lockfile --non-interactive
  - bower install

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup

deploy:
  provider: npm
  email: info@simplabs.com
  api_key:
    secure: pw7jVmECVUo44BZtLq+AKeugpB2Xq1U4AE4BpXjKYt8dk2gKm4kC66FXzNJ4BxueadQFpLZZOES+511nfbfKVPpNEXfyx6Won+LWRHgNFhPuYuiKAVWHP0HjBqRmSHZ5pj5yjs7Gx90Nmuux0kRS7dwh/kOPQmDhWyWgjIqxewCTU6ALlf/KjqaMwAXnVU5PBPo441M0Von/DUqXoGWwzD0ASzQ1gYWjcTQrFUYhvHq3XcHLxJQlyR2Wx5gEuIUs73evvfMuCvR8YKT5I6XrynhtGGBCTFOL52lnSPhyJa8jnFwY5f0F2u7epxu2F4xt/eQeH+Vg2WNvUbtEqRlIytTkAw6OQkxD/RJYlCNg4KhwYhQvbamYFFpDAnuBKqoT1QkcDPnP0KsM9HxgDF+arOvOeqhSpNNfW3j4gMTNE2yQPKpiXu4l8zvtPoSX2flItdYzGydsngMqCFhIftByA15tZoFV373JD6ZmgNE/1skD2jSySopvyNjtrdzWd411eyvg/lzR8kE2aEqjMGwGwANmbFEICPYrN5Vg56ZXCS1tZeyZ/TsEAfbiomrRdK4saFJo58PImEczmEfP+ZiSrFXoN3vb56V/gFhdtyBPS+W9TA1h+/m6y4fQqVrA8pbDKcFRnkcR1YEmF3CbZu0TiWCgK9EhAR/yu6csLF3gteQ=
  on:
    tags: true
    repo: simplabs/ember-cli-pixijs

notifications:
  email: false
  slack:
    rooms:
      secure: OOKD4ZksqzEBW/A3WRuOToODIxnDITqx+Esu7tdmmYPuQlMYgx4SUHv8j9OM9/ScFJiseeVGSkl45vJrHLLIITX9XSjO1RgiGZgw2heVujmGpF6CZNqvT6GsQuKIvMzmwF7IxuHdfV45Csr9Ou/Fg74TszR/4S2h4SOI4zhLg7A=
    on_success: never
